module.exports = {
    testEnvironment: 'jest-environment-jsdom',
    setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],
    moduleNameMapper: {
      '^@/assets/(.*)$': '<rootDir>/assets/$1',
      '^@/pages/(.*)$': '<rootDir>/pages/$1',
      '^@/services/(.*)$': '<rootDir>/services/$1',
      '^@/components/(.*)$': '<rootDir>/components/$1',
      '^@/firebase/(.*)$': '<rootDir>/firebase/$1',
      '^@/hooks/(.*)$': '<rootDir>/hooks/$1',
    },
    transform: {
      '^.+\\.(js|jsx|ts|tsx)$': ['babel-jest', { presets: ['next/babel'] }],
    },
    testPathIgnorePatterns: ['<rootDir>/.next/', '<rootDir>/node_modules/'],
    collectCoverage: true,
    coverageDirectory: 'coverage',
    coverageReporters: ['text', 'lcov'],
    collectCoverageFrom: [
      '<rootDir>/components/**/*.ts',
      '<rootDir>/components/**/*.tsx',
      '<rootDir>/!components/**/*.d.ts',
      '<rootDir>/services/**/*.ts',
      '<rootDir>/services/**/*.tsx',
      '<rootDir>/!services/**/*.d.ts',
      '<rootDir>/firebase/**/*.ts',
      '<rootDir>/firebase/**/*.tsx',
      '<rootDir>/!firebase/**/*.d.ts',
      '<rootDir>/pages/**/*.ts',
      '<rootDir>/pages/**/*.tsx',
      '<rootDir>/!pages/**/*.d.ts',
      '<rootDir>/hooks/**/*.ts',
      '<rootDir>/hooks/**/*.tsx',
      '<rootDir>/!hooks/**/*.d.ts',
    ],
  };
  